---
title: "6_BetaDiv_hipperammon"
output: html_document
date: "2023-06-20"
---
```{r libraries and objects}
library(phyloseq)
library(dplyr)
library(microbiome)

ps_comp <- readRDS("~/Documents/Lola/Datos_CIPF_2023/Rats_HE_HiperAmmon_model/outputs/ps_comp.Rds")
ps_clr <- readRDS("~/Documents/Lola/Datos_CIPF_2023/Rats_HE_HiperAmmon_model/outputs/ps_clr.Rds")
```

#PCoAs relative abundance
###PCoA: Group
```{r PCoA representation}
library(tibble)
library(ggplot2)
library(forcats)
dist = phyloseq::distance(ps_comp, method="bray")
ordination = ordinate(ps_comp, method="PCoA", distance=dist)
plot_ordination(ps_comp, ordination, color="Group") + 
    theme_classic() +
    theme(strip.background = element_blank()) + stat_ellipse(aes(group = Group), linetype = 2)
```

###PCoA: centroid groups
```{r PCoA centroids}
##Bray curtis estimation
bray_matrix<- ps_comp@otu_table %>%
    t() %>%
    as.data.frame() %>%
    # bray-curtis dissimilarity
    vegan::vegdist(method = 'bray',
                   diag = TRUE, upper = TRUE)
metadata_h<-as.data.frame(sample_data(ps_comp))
rownames(metadata_h)<-metadata_h$SampleID
Group<-merge(as.data.frame(as.matrix(bray_matrix)), metadata_h, by="row.names")
Group<-as.vector(rownames(as.data.frame(as.matrix(bray_matrix))))

df <- metadata_h
df<-df[match(Group, df$SampleID),]

## Calculate multivariate dispersion or distance to the centroid
permdisp <- vegan::betadisper(bray_matrix, df$Group, "centroid")

##Plot
plot(permdisp, main="PCoA", hull=FALSE, ellipse=TRUE)
boxplot(permdisp, main="Distance to centroids")

axes<-permdisp$eig[1:3]/sum(permdisp$eig[permdisp$eig > 0]) * 100

plot(permdisp, main="PCoA relative abundance", hull=FALSE, ellipse=TRUE, segments = TRUE, seg.col = c("orange", "pink"), col = c("darkorange3", "magenta4"), label = TRUE, label.cex = 1, pch = c(20, 20, 20), seg.lty = c(1), seg.lwd = 1, xlab = paste0('PCoA ',axes[1], '%'), ylab = paste0('PCoA ',axes[2], '%'))

permdisp$eig[1:3]/sum(permdisp$eig[permdisp$eig > 0]) * 100
```

#PCoAs clr
###PCoA: Group
```{r PCoA representation}
dist = phyloseq::distance(ps_clr, method="euclidean")
ordination = ordinate(ps_clr, method="PCoA", distance=dist)
plot_ordination(ps_clr, ordination, color="Group") + 
    theme_classic() +
    theme(strip.background = element_blank()) + stat_ellipse(aes(group = Group), linetype = 2)
```

###PCoA: centroid groups
```{r centroid groups}
euclidean_matrix<- ps_clr@otu_table %>%
    t() %>%
    as.data.frame() %>%
    # bray-curtis dissimilarity
    vegan::vegdist(method = 'euclidean',
                   diag = TRUE, upper = TRUE)
metadata_h<-as.data.frame(metadata_h)
rownames(metadata_h)<-metadata_h$SampleID
Group<-merge(as.data.frame(as.matrix(euclidean_matrix)), metadata_h, by="row.names")
Group<-as.vector(rownames(as.data.frame(as.matrix(euclidean_matrix))))

df <- metadata_h
df<-df[match(Group, df$SampleID),]

## Calculate multivariate dispersion or distance to the centroid
permdisp <- vegan::betadisper(euclidean_matrix, df$Group, "centroid")

##Plot
axes<-permdisp$eig[1:3]/sum(permdisp$eig[permdisp$eig > 0]) * 100
plot(permdisp, main="PCoA", hull=FALSE, ellipse=TRUE)
boxplot(permdisp, main="Distance to centroids")

plot(permdisp, main="PCoA clr transformed", hull=FALSE, ellipse=TRUE, segments = TRUE, seg.col = c("orange", "pink"), col = c("darkorange3", "magenta4"), label = TRUE, label.cex = 1, pch = c(20, 20, 20), seg.lty = c(1), seg.lwd = 1, xlab = paste0('PCoA ',axes[1], '%'), ylab = paste0('PCoA ',axes[2], '%'))

```


#PERMANOVA and Top taxa
```{r permanova types}
#PERMANOVA
otu <- abundances(ps_clr)
meta <- meta(ps_clr)
permanova <- adonis(t(otu) ~ Type,
                    data = meta, permutations=999, method = "euclidean", by = NULL)

# P-value
permanova$aov.tab

# Analysis of Variance Table
otu <- abundances(ps_clr)
dist <- vegdist(t(otu), method = "euclidean")
meta <- meta(ps_clr)
anova(betadisper(dist, meta$Type))

coef <- coefficients(permanova)["Type1",]
top.coef <- coef[rev(order(abs(coef)))[1:20]]
par(mar = c(3, 14, 2, 1))
barplot(sort(top.coef), horiz = T, las = 1, main = "Top taxa")
```

#PERMANOVA subsetting
```{r permanova types}
otu <- abundances(ps_clr)
meta <- meta(ps_clr)

library(vegan)
permanova <- adonis(t(otu) ~ Group,
                    data = meta, permutations=999, method = "euclidean")
# P-value
print(as.data.frame(permanova$aov.tab)["Group", "Pr(>F)"])

# Analysis of Variance Table
permanova$aov.tab
```

#Comparison distance to centroids
```{r permanova types}
library(vegan)
library(usedist)
euclidean_matrix<- ps_clr@otu_table %>%
    t() %>%
    as.data.frame() %>%
    # bray-curtis dissimilarity
    vegan::vegdist(method = 'euclidean',
                   diag = TRUE, upper = TRUE)
metadata_h<-as.data.frame(sample_data(ps_clr))
rownames(metadata_h)<-metadata_h$SampleID
Type<-merge(as.data.frame(as.matrix(euclidean_matrix)), metadata_h, by="row.names")
Type<-as.vector(rownames(as.data.frame(as.matrix(euclidean_matrix))))

df <- metadata_h
df<-df[match(Type, df$SampleID),]

## Calculate multivariate dispersion or distance to the centroid
permdisp <- vegan::betadisper(euclidean_matrix, df$Type, "centroid")

TukeyHSD(permdisp)
anova(permdisp)

MHE<-subset(df, Type=="MHE")
MHE<-as.vector(MHE$SampleID)

Without_MHE<-subset(df, Type=="Without_MHE")
Without_MHE<-as.vector(Without_MHE$SampleID)

MCI<-subset(df, Type=="MCI")
MCI<-as.vector(MCI$SampleID)

NMCI<-subset(df, Type=="NMCI")
NMCI<-as.vector(NMCI$SampleID)

Control<-subset(df, Type=="Control")
Control<-as.vector(Control$SampleID)

#Distance between groups of interest centroids
dist_between_centroids(euclidean_matrix, idx1=Control, idx2 = MHE)
dist_between_centroids(euclidean_matrix, idx1=Control, idx2 = Without_MHE)
dist_between_centroids(euclidean_matrix, idx1=Control, idx2 = MCI)
dist_between_centroids(euclidean_matrix, idx1=Control, idx2 = NMCI)
dist_between_centroids(euclidean_matrix, idx1=MHE, idx2 = Without_MHE)
dist_between_centroids(euclidean_matrix, idx1=MCI, idx2 = NMCI)

#Mean distances of samples to centroid of each group
permdisp[["group.distances"]]
usedist::dist_to_centroids(dist, df$Type)

```


#RNA later PCoAs
```{r RNA later general}
library(phyloseq)
library(dplyr)
library(microbiome)

ps_comp <- readRDS("~/Documents/Lola/Datos_CIPF_2023/Rats_HE_HiperAmmon_model/outputs/ps_comp.Rds")
ps_clr <- readRDS("~/Documents/Lola/Datos_CIPF_2023/Rats_HE_HiperAmmon_model/outputs/ps_clr.Rds")

library(tibble)
library(ggplot2)
library(forcats)
dist = phyloseq::distance(ps_comp, method="bray")
ordination = ordinate(ps_comp, method="PCoA", distance=dist)
plot_ordination(ps_comp, ordination, color="RNA_later") + 
    theme_classic() +
    theme(strip.background = element_blank()) + stat_ellipse(aes(group = RNA_later), linetype = 2)

dist = phyloseq::distance(ps_clr, method="euclidean")
ordination = ordinate(ps_clr, method="PCoA", distance=dist)
plot_ordination(ps_clr, ordination, color="RNA_later") + 
    theme_classic() +
    theme(strip.background = element_blank()) + stat_ellipse(aes(group = RNA_later), linetype = 2) 
```

```{r RNA only repeated samples}
ps_repeated<-subset_samples(ps_clr, Repeated=="Yes")
samples<-(c("PC258", "PC258", "PC261", "PC261", "PN082", "PN082", "PN088", "PN088"))
data<-data.frame(sample_data(ps_repeated))
data$samples<-samples
sample_data(ps_repeated)<-data
dist = phyloseq::distance(ps_repeated, method="euclidean")
ordination = ordinate(ps_repeated, method="PCoA", distance=dist)
plot_ordination(ps_repeated, ordination, color="RNA_later", axes = c(1,2)) + 
    theme_classic() +
    theme(strip.background = element_blank()) + stat_ellipse(aes(group = RNA_later), linetype = 2) +
    geom_line(aes(group = samples))

euclidean_matrix<- ps_repeated@otu_table %>%
    t() %>%
    as.data.frame() %>%
    # bray-curtis dissimilarity
    vegan::vegdist(method = 'euclidean',
                   diag = TRUE, upper = TRUE)
metadata_h<-as.data.frame(metadata_h)
rownames(metadata_h)<-metadata_h$SampleID
RNA_later<-merge(as.data.frame(as.matrix(euclidean_matrix)), metadata_h, by="row.names")
RNA_later<-as.vector(rownames(as.data.frame(as.matrix(euclidean_matrix))))

df <- metadata_h
df<-df[match(RNA_later, df$SampleID),]

## Calculate multivariate dispersion or distance to the centroid
permdisp <- vegan::betadisper(euclidean_matrix, df$RNA_later, "centroid")

##Plot
axes<-permdisp$eig[1:3]/sum(permdisp$eig[permdisp$eig > 0]) * 100
plot(permdisp, main="PCoA", hull=TRUE, ellipse=FALSE, segments = FALSE, xlab = paste0('PCoA ',axes[1], '%'), ylab = paste0('PCoA ',axes[2], '%')) 
text(permdisp$vectors, y =NULL, labels = rownames(permdisp$vectors))

#Distance of each sample to the centroid (all axis)
permdisp[["distances"]]

#Distance of each sample to the centroid (PCoA1 and PCoA2)
centroids<-permdisp[["centroids"]]
centroids<-subset(centroids, select = c(PCoA1, PCoA2))
test<- data.frame()
##Distance to No RNA later to centroid from each sample
for (i in 1:8) {
    print(sqrt((centroids$PCoA1[1]-(vectors$Axis.1[i]))^2+(centroids$PCoA2[1]-vectors$Axis.2[i])^2))
}
##Distance to Yes RNA later to centroid from each sample
for (i in 1:8) {
    print(sqrt((centroids$PCoA1[2]-(vectors$Axis.1[i]))^2+(centroids$PCoA2[2]-vectors$Axis.2[i])^2))
}

#Distance between samples (PCoA1 and PCoA2)
vectors<- as.data.frame(ordination[["vectors"]])
vectors<-subset(vectors, select = c(Axis.1, Axis.2))
vectors

print(sqrt(((vectors$Axis.1[1])-(vectors$Axis.1[2]))^2+(vectors$Axis.2[1]-vectors$Axis.2[2])^2))
sqrt((-13.03848-(-16.83453))^2+(6.140282-9.027057)^2)
#[1] 4.769011

print(sqrt(((vectors$Axis.1[3])-(vectors$Axis.1[4]))^2+(vectors$Axis.2[3]-vectors$Axis.2[4])^2))
sqrt((33.45307-(32.77063))^2+(27.977083-28.531009)^2)s.2[6])^2))
sqrt((16.94437-(19.69500))^2+(-45.352191-(-32.587515))^2)
#[1] 13.05768
#[1] 0.878953

print(sqrt(((vectors$Axis.1[5])-(vectors$Axis.1[6]))^2+(vectors$Axis.2[5]-vectors$Axi

print(sqrt(((vectors$Axis.1[7])-(vectors$Axis.1[8]))^2+(vectors$Axis.2[7]-vectors$Axis.2[8])^2))
sqrt((-36.47854-(-36.51151))^2+(3.680894-(2.583381))^2)
#[1] 1.098008
```